### ISSUE TITLE
报错查找！！！

### ISSUE THREAD

**Issue by yangtzelsl** [zhaoxingfeng/PCA#1]
![default](https://user-images.githubusercontent.com/33994422/39797375-5223aef6-538e-11e8-9480-56cbd814c5e9.png)
请问这是哪里出错了呢？

**Comment by zhaoxingfeng** [comment]
你好，看错误提示貌似你的pd.series索引为int类型，你在使用get_loc时可能给了string类型。当然只是猜测，如果要分析原因最好能贴代码，如果已经解决请忽略。




在 2018-05-09 13:39:22，"yangtzelsl" <notifications@github.com> 写道：



请问这是哪里出错了呢？

**Comment by yangtzelsl** [comment]
嗯，代码完全用的是您github上的代码，暂时未做修改，运行初报了这个错误，不知如何解决

**Comment by yangtzelsl** [comment]
代码还是您的代码；报错如下：
C:\software\Anaconda3\python.exe D:/python/Machine-Learning-master/PCA/PCA_test02.py
Traceback (most recent call last):
  File "pandas\_libs\index.pyx", line 154, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 759, in pandas._libs.hashtable.Int64HashTable.get_item
TypeError: an integer is required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\software\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2442, in get_loc
    return self._engine.get_loc(key)
  File "pandas\_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 156, in pandas._libs.index.IndexEngine.get_loc
KeyError: range(0, 4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandas\_libs\index.pyx", line 154, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 759, in pandas._libs.hashtable.Int64HashTable.get_item
TypeError: an integer is required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/python/Machine-Learning-master/PCA/PCA_test02.py", line 82, in <module>
    data, label = df[range(len(df.columns) - 1)], df[[len(df.columns) - 1]]
  File "C:\software\Anaconda3\lib\site-packages\pandas\core\frame.py", line 1964, in __getitem__
    return self._getitem_column(key)
  File "C:\software\Anaconda3\lib\site-packages\pandas\core\frame.py", line 1971, in _getitem_column
    return self._get_item_cache(key)
  File "C:\software\Anaconda3\lib\site-packages\pandas\core\generic.py", line 1645, in _get_item_cache
    values = self._data.get(item)
  File "C:\software\Anaconda3\lib\site-packages\pandas\core\internals.py", line 3590, in get
    loc = self.items.get_loc(item)
  File "C:\software\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2444, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 156, in pandas._libs.index.IndexEngine.get_loc
KeyError: range(0, 4)

Process finished with exit code 1

**Comment by zhaoxingfeng** [comment]
找到原因了。你使用的是python3，在python3中range函数返回的是一个可迭代对象，而非python2中的list，所以会提示get_loc需要int类型。
改正：data, label = df[list(range(len(df.columns) - 1))], df[[len(df.columns) - 1]] 即可

**Comment by zhaoxingfeng** [comment]
@yangtzelsl 找到原因了。你使用的是python3，在python3中range函数返回的是一个可迭代对象，而非python2中的list，所以会提示get_loc需要int类型。
改正：data, label = df[list(range(len(df.columns) - 1))], df[[len(df.columns) - 1]] 即可。

**Comment by yangtzelsl** [comment]
哦哦，原来是这样，非常感谢大神耐心解决，根本不知道还有这种区别，再次测试过，成功了，谢谢谢谢！
